export const images = {
  image_avatar: require('./image_avatar.png'),
  logo_1: require('./Logo_1.png'),
  forgot_password: require('./forgot_password.png'),
  change_password: require('./change_password.png'),
  Icon_chat: require('./Icon_chat.png'),
  Icon_search: require('./Icon_search.png'),
  Icon_notify: require('./Icon_notify.png'),
  Icon_giohang: require('./Icon_giohang.png'),
  icon_camera: require('./icon_camera.png'),
  Banner_QC: require('./Banner_QC.png'),
  icon_yte: require('./icon_yte.png'),
  banner_yte: require('./banner_yte.png'),
  icon_chon_dv: require('./icon_chon_dv.png'),
  icon_dv_bosung: require('./icon_dv_bosung.png'),
  icon_book: require('./icon_book.png'),
  memo_pencil: require('./memo-pencil.png'),
  image_doanh_thu: require('./image_doanh_thu.png'),
  icon_note: require('./icon_note.png'),
  image_phieu_yc: require('./image_phieu_yc.png'),
  image_danh_gia: require('./image_danh_gia.png'),
  iconBack: require('./IconBack.png'),
  iconEnter: require('./iconEnter.png'),
  iconHappy:require('./iconHappy.png'),
  iconGhim:require('./iconGhim.png'),
  iconPayment:require('./iconPayment.png'),
  icon_notifi_detail:require('./icon_notifi_detail.png'),
  icon_work:require('./icon_work.png'),
};